### PR TITLE
Compatibility with PHP 7.1

### PR DESCRIPTION
**Pull request by lipemat**
1. Cleaned up a few deprecated items.
2. Improved a couple PHP Docs
3. Fix issue with extra blank line after ?> tag
4. Fixed clash between function and classname

I adjusted the WP_Syntax function to fix the clash with the WP_Syntax class, however I'm not convinced that this is the better approach vs adjusting the class name. It really depends on how your docs read. If they suggest using the function it's probably better to adjust the class name, or vise versa. One must change but for backward compatibility it's best to change the one not referred to as often in docs.

### CODE REVIEW

**Comment by shazahm1** [comment]
Thanks for the pull!

If you fetch my dev branch, I think you'll find most everything from your commits taken care of. The one main exception is this https://github.com/shazahm1/WP-Syntax/pull/22/commits/12422aa042af7724583a5bba21e5b286d2374c4f. There's no clash, it functions just fine in PHP 7.1. I've tested and run on my own production site.

**Comment by codepo8** [comment]
That's not true. The plugin was broken on my setup (christianheilmann.com) until I merged lipemat's fix. Can you ensure the renaming of the class is applied?

**Comment by shazahm1** [comment]
@codepo8 

What exact is "broken"? The current release (version 1.1) found in wp.org was updated for PHP7.1 compatibility.

**Comment by codepo8** [comment]
I'm on a self-hosted instance on MediaTemple using 7.0.6 CGI stable and it didn't apply the plugin at all.

**Comment by shazahm1** [comment]
Anything appear in the PHP error log? I suggest turning on all PHP errors and notices to learn if there is a reason it was not working.

**Comment by codepo8** [comment]
Nothing in the error log, turning on reporting also yields nothing. 

https://www.christianheilmann.com/2016/09/29/quick-tip-using-modulo-to-re-start-loops-without-the-need-of-an-if-statement/

Now has error reporting on and as you can see the pre elements do not get changed.

**Comment by shazahm1** [comment]
@codepo8 

Took a look at the page and its source, love the easter egg!

Are you sure your theme has the wp_header and wp_footer templates tags?

**Comment by codepo8** [comment]
That fixed it. Duh :) 
Thanks!

**Comment by shazahm1** [comment]
@codepo8 

Great to hear it's working now!

**Pull request closed without merging**
